# Generated by Django 6.0 on 2026-01-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
