# Generated by Django 6.0 on 2026-01-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_profile_branch_remove_profile_user_register_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
