# Generated by Django 6.0 on 2026-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
