# Generated by Django 6.0 on 2026-01-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_register_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
