# Generated by Django 6.0 on 2026-01-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_register_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile/'),
        ),
    ]
