# Generated by Django 6.0 on 2025-12-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
