# Generated by Django 6.0 on 2025-12-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bank_system', '0002_branch_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='Profile',
        ),
    ]
