# Generated by Django 6.0 on 2025-12-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
