# Generated by Django 6.0 on 2026-01-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Response',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
