# Generated by Django 6.0 on 2026-01-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disable_request',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
