# Generated by Django 6.0 on 2026-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_disable_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disable_request',
            field=models.CharField(blank=True, default='no requests', max_length=500),
        ),
    ]
