# Generated by Django 6.0 on 2026-01-05 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='Type',
        ),
        migrations.AddField(
            model_name='statement',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('deduct', 'Deduct')], max_length=10),
        ),
        migrations.AlterField(
            model_name='statement',
            name='bal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL),
        ),
    ]
